"""donut"""
def main():
    """donut"""
    _ = input()
    print("             i,j,k,x,y,o,N;")
    print("         main(){float z[1760],a")
    print("      #define R(t,x,y) f=x;x-=t*y\\")
    print("   ;y+=t*f;f=(3-x*x-y*y)/2;x*=f;y*=f;")
    print("   =0,e=1,c=1,d=0,f,g,h,G,H,A,t,D;char")
    print(" b[1760];for(;;){memset(b,32,1760);g=0,")
    print("h=1;memset(z,0,7040);for(j=0;j<90;j++){")
    print("G=0,H=1;for(i=0;i<314;i++){A=h+2,D=1/(G*")
    print("A*a+g*e+5);t=G*A        *e-g*a;x=40+30*D")
    print("*(H*A*d-t*c);y=          12+15*D*(H*A*c+")
    print("t*d);o=x+80*y;N          =8*((g*a-G*h*e)")
    print("*d-G*h*a-g*e-H*h        *c);if(22>y&&y>")
    print(" 0&&x>0&&80>x&&D>z[o]){z[o]=D;b[o]=(N>0")
    print("  ?N:0)[\".,-~:;=!*#$@\"];}R(.02,H,G);}R(")
    print("  .07,h,g);}for(k=0;1761>k;k++)putchar")
    print("   (k%80?b[k]:10);R(.04,e,a);R(.02,d,")
    print("     c);usleep(15000);printf('\\n'+(")
    print("        \" donut.c! \\x1b[23A\"));}}")
    print("          /*no math lib needed")
    print("             .@a1k0n 2021.*/")
main()
