'''food'''
def main():
    num1 = int(input())
    num2 = int(input())
    num3 = int(input())
    num4 = int(input())
    num5 = int(input())
    num6 = int(input())
    num7 = int(input())
    num8 = int(input())
    num9 = int(input())
    num10 = int(input())
    num11 = int(input())
    num12 = int(input())
    num13 = int(input())
    num14 = int(input())
    num15 = int(input())
    num16 = int(input())
    num17 = int(input())
    num18 = int(input())
    num19 = int(input())
    num20 = int(input())
    num21 = int(input())
    num22 = int(input())
    num23 = int(input())
    num24 = int(input())
    total = num1, num2, num3, num4, num5, num6, num7, num8, num9, num10, num11, num12,\
          num13, num14, num15, num16, num17, num18, num19, num20, num21, num22, num23, num24
    print(total)
main()
